<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706131002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_pub_activity (id UUID NOT NULL, published TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(32) NOT NULL, payload JSON NOT NULL, actor_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68FDF7B210DAF24A ON activity_pub_activity (actor_id)');
        $this->addSql('CREATE TABLE activity_pub_actor (id UUID NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subject_type VARCHAR(32) NOT NULL, subject_id VARCHAR(64) NOT NULL, username VARCHAR(190) NOT NULL, public_key_pem TEXT NOT NULL, private_key_pem TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_activity_pub_actor_username ON activity_pub_actor (username)');
        $this->addSql('CREATE UNIQUE INDEX uniq_activity_pub_actor_subject ON activity_pub_actor (subject_type, subject_id)');
        $this->addSql('CREATE TABLE activity_pub_follower (id UUID NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, remote_actor_iri VARCHAR(500) NOT NULL, remote_inbox_url VARCHAR(500) NOT NULL, actor_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D5FF7AE10DAF24A ON activity_pub_follower (actor_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_activity_pub_follower ON activity_pub_follower (actor_id, remote_actor_iri)');
        $this->addSql('CREATE TABLE post (id UUID NOT NULL, published TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DF675F31B ON post (author_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, preferred_locale VARCHAR(5) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        $this->addSql('ALTER TABLE activity_pub_activity ADD CONSTRAINT FK_68FDF7B210DAF24A FOREIGN KEY (actor_id) REFERENCES activity_pub_actor (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_pub_follower ADD CONSTRAINT FK_7D5FF7AE10DAF24A FOREIGN KEY (actor_id) REFERENCES activity_pub_actor (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_pub_activity DROP CONSTRAINT FK_68FDF7B210DAF24A');
        $this->addSql('ALTER TABLE activity_pub_follower DROP CONSTRAINT FK_7D5FF7AE10DAF24A');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8DF675F31B');
        $this->addSql('DROP TABLE activity_pub_activity');
        $this->addSql('DROP TABLE activity_pub_actor');
        $this->addSql('DROP TABLE activity_pub_follower');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE users');
    }
}
